// The balance report: npm run balance. Plays 1,000 whole runs of Greenmarch at 70%, 85% and 95% tap accuracy
// (random node choices on each act's map), prints the table and writes docs/balance.md.
import { writeFileSync } from 'node:fs';
import { it } from 'vitest';
import { balance, type ActRow } from '../../src/core/bot';
import { cloneTuning } from '../../src/core/tuning';

const RUNS = Number(process.env.RUNS ?? 1000);
const ACCURACIES = [0.7, 0.85, 0.95];

const pct = (v: number) => (Number.isFinite(v) ? `${Math.round(v * 100)}%` : '-');
const sec = (v: number) => (Number.isFinite(v) ? `${Math.round(v)} s` : '-');
const num = (v: number) => (Number.isFinite(v) ? v.toFixed(1) : '-');

function table(rows: ActRow[]): string {
  const head = '| Player | Act | Reached | First-try clear | Clear (6 tries) | Avg tries | Boss first fight won | Fight / elite / boss | HP going into boss | Boss HP / max finisher | Hero attack entering |';
  const sep = '|---|---|---|---|---|---|---|---|---|---|---|';
  const body = rows.map(
    (r) =>
      `| ${pct(r.accuracy)} | ${r.act + 1} | ${pct(r.reached / r.runs)} | **${pct(r.firstTry)}** | ${pct(r.clearRate)} | ${num(r.attempts)} | **${pct(r.bossFirstTry)}** | ${sec(r.fightSec)} / ${sec(r.eliteSec)} / ${sec(r.bossSec)} | ${pct(r.hpAtBoss)} | ${num(r.bossVsMaxFinisher)} | ${num(r.heroAtk)} |`,
  );
  return [head, sep, ...body].join('\n');
}

function losses(rows: ActRow[]): string {
  const head = '| Player | Act | Lost attempts at: fight | elite | boss | Misses per tap | Hits taken per min | Specials per min | Finisher share of damage |';
  const sep = '|---|---|---|---|---|---|---|---|---|';
  const body = rows.map(
    (r) =>
      `| ${pct(r.accuracy)} | ${r.act + 1} | ${r.lostAt.fight ?? 0} | ${r.lostAt.elite ?? 0} | ${r.lostAt.boss ?? 0} | ${pct(r.missRate)} | ${num(r.hitsTakenPerMin)} | ${num(r.specialsPerMin)} | ${pct(r.finisherShare)} |`,
  );
  return [head, sep, ...body].join('\n');
}

it('balance report', () => {
  const t = cloneTuning();
  const t0 = Date.now();
  const rows = balance(t, ACCURACIES, RUNS);
  const at = (acc: number, act: number) => rows.find((r) => r.accuracy === acc && r.act === act)!;
  const [a1, a2, a3] = [0, 1, 2].map((a) => at(0.85, a));
  const md = `# Balance report: Region 1, Greenmarch

Generated by \`npm run balance\` (\`tests/balance/balance.run.ts\`, bot in \`src/core/bot.ts\`): ${RUNS} whole runs per
accuracy, ${Math.round((Date.now() - t0) / 1000)} s to run.

**The bot** plays the real simulation at 120 Hz:

- It aims at the next block the cursor will reach (never a purple trap on purpose) and taps at most every 120 ms.
- Accuracy is the share of its taps that are well timed (inside the block, often in the perfect zone). The rest land
  60-200 ms early or late, wherever that is. Accuracy slips 6% per 1x of cursor speed above base.
- It reads telegraphs like a person: while a Hedge Knight's shield is up it holds off yellow (as often as its
  accuracy), and it waits out a frozen cursor. Spores and shell blocks are just more blocks to tap.
- It cashes in the finisher when waiting for another stack isn't worth the risk of a combo break.
- On the map it picks the next node **at random**. It takes Full Heal when hurt (otherwise the rarest card), always
  rests, buys a potion when hurt and then the rarest cards it can afford, and picks event choices at random.
- A lost act is retried from its start (up to 6 tries), with the hero and coins as they entered it; a cleared act
  carries the hero (healed to full) into the next.

## Targets (assumptions from the planning chat; the playtester asked for a challenge)

| Target | Result (85% player) |
|---|---|
| Clears each act first try 70-85% of the time | Act 1 **${pct(a1.firstTry)}**, Act 2 **${pct(a2.firstTry)}**. Act 3 ends in the Boar King, so its first-try clear is capped by him: **${pct(a3.firstTry)}** |
| Beats the Boar King first try 40-60% of the time | **${pct(a3.bossFirstTry)}** of first fights against him are won; ${pct(a3.clearRate)} clear Act 3 within 6 tries |
| Every boss needs at least two max-stack finishers | ${num(a1.bossVsMaxFinisher)} / ${num(a2.bossVsMaxFinisher)} / ${num(a3.bossVsMaxFinisher)}, never one-shot |
| Mini-bosses | Bandit Captain ${pct(a1.bossFirstTry)} and Ruin Golem ${pct(a2.bossFirstTry)} first-fight wins |

## Results

${table(rows)}

## Where runs are lost

${losses(rows)}

Notes:

- "First-try clear" counts runs that cleared the act without dying (the revive can be used). "Boss first fight won" is
  the share of runs whose first fight against the act's boss was won.
- Act numbers scale enemy HP and attack per act (\`tuning.acts\`), plus ${Math.round(t.map.rowHp * 100)}% more enemy HP per
  map row. HP carries from node to node (kills heal only ${Math.round(t.hero.healOnKill * 100)}%), so rests, potions and Full
  Heal cards matter.
`;
  writeFileSync('docs/balance.md', md);
  process.stderr.write(`${table(rows)}\n${losses(rows)}\n`);
}, 1_800_000);
