// The balance report: npm run balance. Plays 1,000 whole runs of Greenmarch for a 55%, 70%, 85% and 95% player
// (random node choices on each act's map), prints the table and writes docs/balance.md.
import { writeFileSync } from 'node:fs';
import { it } from 'vitest';
import { balance, timingSpread, type ActRow } from '../../src/core/bot';
import { cloneTuning } from '../../src/core/tuning';

const RUNS = Number(process.env.RUNS ?? 1000);
const ACCURACIES = [0.55, 0.7, 0.85, 0.95];

const pct = (v: number) => (Number.isFinite(v) ? `${Math.round(v * 100)}%` : '-');
const sec = (v: number) => (Number.isFinite(v) ? `${Math.round(v)} s` : '-');
const num = (v: number) => (Number.isFinite(v) ? v.toFixed(1) : '-');

function table(rows: ActRow[]): string {
  const head = '| Player | Act | Reached | First-try clear | Clear (6 tries) | Avg tries | Boss first fight won | Fight / elite / boss | HP going into boss | Boss HP / max finisher | Hero attack entering |';
  const sep = '|---|---|---|---|---|---|---|---|---|---|---|';
  const body = rows.map(
    (r) =>
      `| ${pct(r.accuracy)} | ${r.act + 1} | ${pct(r.reached / r.runs)} | **${pct(r.firstTry)}** | ${pct(r.clearRate)} | ${num(r.attempts)} | **${pct(r.bossFirstTry)}** | ${sec(r.fightSec)} / ${sec(r.eliteSec)} / ${sec(r.bossSec)} | ${pct(r.hpAtBoss)} | ${num(r.bossVsMaxFinisher)} | ${num(r.heroAtk)} |`,
  );
  return [head, sep, ...body].join('\n');
}

function losses(rows: ActRow[]): string {
  const head = '| Player | Act | Lost attempts at: fight | elite | boss | Misses per tap | Hits taken per min | Specials per min | Finisher share of damage |';
  const sep = '|---|---|---|---|---|---|---|---|---|';
  const body = rows.map(
    (r) =>
      `| ${pct(r.accuracy)} | ${r.act + 1} | ${r.lostAt.fight ?? 0} | ${r.lostAt.elite ?? 0} | ${r.lostAt.boss ?? 0} | ${pct(r.missRate)} | ${num(r.hitsTakenPerMin)} | ${num(r.specialsPerMin)} | ${pct(r.finisherShare)} |`,
  );
  return [head, sep, ...body].join('\n');
}

it('balance report', () => {
  const t = cloneTuning();
  const t0 = Date.now();
  const rows = balance(t, ACCURACIES, RUNS);
  const at = (acc: number, act: number) => rows.find((r) => r.accuracy === acc && r.act === act)!;
  const [a1, a2, a3] = [0, 1, 2].map((a) => at(0.85, a));
  const c1 = at(0.7, 0);
  const b1 = at(0.55, 0);
  const ms = (acc: number) => Math.round(timingSpread(t, acc) * 1000);
  const md = `# Balance report: Region 1, Greenmarch

Generated by \`npm run balance\` (\`tests/balance/balance.run.ts\`, bot in \`src/core/bot.ts\`): ${RUNS} whole runs per
accuracy, ${Math.round((Date.now() - t0) / 1000)} s to run.

**The bot plays like a person, not a machine.** It plays the real simulation at 120 Hz:

- It aims at the next block the cursor will reach (never a purple trap on purpose), blocking a red first when it
  can't get both, and taps at most every 140 ms (a thumb).
- It only taps blocks it has had time to see: a block must have been on the bar 250 ms (reds, which always come in
  from the right end, 175 ms) before the tap.
- Each tap is aimed at the moment the cursor crosses the block's center and is off by a human timing error: a normal
  spread in milliseconds, plus 3% lapses (80-250 ms off). The real judge then decides what the tap lands on. So
  thin blocks, fast reds and a fast cursor are as hard for the bot as for a person: a block the cursor crosses in
  60 ms is missed far more often than one it crosses in 150 ms.
- "Accuracy" names the player: the share of plain yellow blocks they hit at the starting cursor speed. A 55% player
  has a timing spread of ${ms(0.55)} ms, 70% ${ms(0.7)} ms, 85% ${ms(0.85)} ms, 95% ${ms(0.95)} ms (one standard deviation).
- It reads telegraphs like a person: while a Hedge Knight's shield is up it holds off yellow (as often as its
  accuracy), and it waits out a frozen cursor. Spores and shell blocks are just more blocks to tap.
- It cashes in the finisher when waiting for another stack isn't worth the risk of a combo break.
- On the map it picks the next node **at random**. It takes Full Heal when hurt (otherwise the rarest card), always
  rests, buys a potion when hurt and then the rarest cards it can afford, and picks event choices at random.
- A lost act is retried from its start (up to 6 tries), with the hero and coins as they entered it; a cleared act
  carries the hero (healed to full) into the next.

## Targets (the playtester found Act 1 too hard: a gentle start, then a ramp)

| Target | Result |
|---|---|
| Act 1 is a gentle start: nearly everyone clears it first try | 85% player **${pct(a1.firstTry)}**, 70% player **${pct(c1.firstTry)}**, 55% player **${pct(b1.firstTry)}** |
| Act 2: an 85% player clears it first try about 80-90% of the time | **${pct(a2.firstTry)}** |
| The Boar King wins his first fight against an 85% player about 35-50% of the time | the player wins **${pct(a3.bossFirstTry)}** of first fights; ${pct(a3.clearRate)} clear Act 3 within 6 tries |
| No boss can be one-shot by a max-stack finisher | boss HP / max finisher ${num(a1.bossVsMaxFinisher)} / ${num(a2.bossVsMaxFinisher)} / ${num(a3.bossVsMaxFinisher)}; one-shots ${pct(a1.bossOneShotRate)} / ${pct(a2.bossOneShotRate)} / ${pct(a3.bossOneShotRate)} (the mini-bosses' half-HP moves are phase gates) |
| Mini-bosses | Bandit Captain ${pct(a1.bossFirstTry)} and Ruin Golem ${pct(a2.bossFirstTry)} first-fight wins (85% player) |

## Results

${table(rows)}

## Where runs are lost

${losses(rows)}

Notes:

- "First-try clear" counts runs that cleared the act without dying (the revive can be used). "Boss first fight won" is
  the share of runs whose first fight against the act's boss was won.
- Act numbers scale enemy HP and attack per act (\`tuning.acts\`), plus ${Math.round(t.map.rowHp * 100)}% more enemy HP per
  map row. HP carries from node to node (kills heal only ${Math.round(t.hero.healOnKill * 100)}%), so rests, potions and Full
  Heal cards matter.
`;
  writeFileSync('docs/balance.md', md);
  process.stderr.write(`${table(rows)}\n${losses(rows)}\n`);
}, 1_800_000);
