// The balance report: npm run balance. Plays 1,000 runs of each level at 70%, 85% and 95% tap accuracy with the
// M1 defaults ("before") and the current defaults ("after"), prints the table and writes docs/balance.md.
import { writeFileSync } from 'node:fs';
import { it } from 'vitest';
import { balance, type BalanceRow } from '../../src/core/bot';
import { cloneTuning, mergeKnown } from '../../src/core/tuning';

const RUNS = Number(process.env.RUNS ?? 1000);
const ACCURACIES = [0.7, 0.85, 0.95];

/** The M1 combat numbers before balancing (block widths vary, boost rarity and level carry-over apply, as now). */
const BEFORE = {
  judge: { missSelfDamage: 3 },
  blocks: { bombDamage: 15, groupSpawnMult: 1.6 },
  hero: { comboPower: 6, healOnKill: 0.15 },
  meter: { stackExp: 1.9 },
  kill: { comboPower: 0.5 },
  boosts: { damage: 0.2, comboPower: 1 },
  enemies: { slime: { hp: 150, atk: 8 }, boar: { hp: 220, atk: 10 }, bandit: { hp: 280, atk: 12 }, bigSlime: { hp: 520, atk: 14 } },
  levels: [
    { name: 'Level 1', theme: 'forest', hpMult: 1, atkMult: 1, stages: [['slime'], ['boar'], ['bandit'], ['bigSlime']] },
    { name: 'Level 2', theme: 'ruins', hpMult: 1, atkMult: 1, stages: [['slime', 'slime', 'bandit']] },
  ],
};

const pct = (v: number) => (Number.isFinite(v) ? `${Math.round(v * 100)}%` : '-');
const sec = (v: number) => (Number.isFinite(v) ? `${v.toFixed(1)} s` : '-');
const num = (v: number) => (Number.isFinite(v) ? v.toFixed(2) : '-');

function table(rows: BalanceRow[]): string {
  const head = '| Accuracy | Level | Reached | First-try win | Tries to clear | Fight per stage | Avg fight | Finisher share | Boss HP / one max finisher | Boss one-shot | Hero attack entering |';
  const sep = '|---|---|---|---|---|---|---|---|---|---|---|';
  const body = rows.map(
    (r) =>
      `| ${pct(r.accuracy)} | ${r.level + 1} | ${pct(r.reached / r.runs)} | ${pct(r.winRate)} | ${num(r.attempts)} | ${r.stageSec.map((s) => s.toFixed(0)).join(' / ')} s | ${sec(r.avgFightSec)} | ${pct(r.finisherShare)} | ${num(r.bossVsMaxFinisher)} | ${pct(r.bossOneShotRate)} | ${r.heroAtk.toFixed(1)} |`,
  );
  return [head, sep, ...body].join('\n');
}

it('balance report', () => {
  const before = cloneTuning();
  mergeKnown(before, BEFORE);
  const after = cloneTuning();
  const t0 = Date.now();
  const b = balance(before, ACCURACIES, RUNS);
  const a = balance(after, ACCURACIES, RUNS);
  const row = (acc: number, level: number) => a.find((r) => r.accuracy === acc && r.level === level)!;
  const a1 = row(0.85, 0);
  const a2 = row(0.85, 1);
  const L = after.levels[1];
  const md = `# Balance report

Generated by \`npm run balance\` (\`tests/balance/balance.run.ts\`, bot in \`src/core/bot.ts\`): ${RUNS} whole runs per
accuracy, ${Math.round((Date.now() - t0) / 1000)} s to run.

**The bot** plays the real simulation at 120 Hz:

- It aims at the next block the cursor will reach (never a purple trap on purpose) and taps at most every 120 ms.
- Accuracy is the share of its taps that are well timed (inside the block, often in the perfect zone). The rest land
  60-200 ms early or late, wherever that is.
- Accuracy slips 6% per 1x of cursor speed.
- It swipes the finisher when it kills, at max stacks, or when waiting for another stack isn't worth the risk of a
  combo break.
- It takes Full Heal when below half HP, otherwise the rarest boost card. Classic mode (misses cost HP).

**A run** is played the way a person plays it:

- Level 1 starts with a fresh hero. A defeat means a retry with the hero as they entered the level (up to 6 tries).
- Each next level starts with the hero and every upgrade they earned, healed at the chest.
- "First-try win" counts the players who reached the level; "Tries to clear" counts the ones who cleared it.

**Targets:**

- From the planning chat: an 85% player wins Level 1 about 80-90% of the time; the boss needs at least 2 max-stack
  finishers (one must not one-shot it); kill growth must not snowball.
- From the playtester: enemies ramp up through a level from easy to tough, and later levels bring more enemies,
  still ramping up, so the upgrades matter.
- The planning chat's 20-60 s fight target now applies to the boss end of each level. First fights are short on
  purpose.

## After (current defaults)

${table(a)}

## Before (M1 numbers, under the same rules)

${table(b)}

## What changed

| Number | M1 | Now | Why |
|---|---|---|---|
| Enemy HP (Slime / Boar / Bandit / Big Slime) | 150 / 220 / 280 / 520 | 350 / 600 / 900 / 3000 | A ramp: a quick first fight, a real boss |
| Enemy attack | 8 / 10 / 12 / 14 | 12 / 16 / 18 / 22 | Pressure: 85% clears Level 1 first try about 9 times in 10 |
| Level 2 | one fight: 2 Slimes + Bandit | 4 stages, 2 then 2 then 3 then the boss with 2 adds; enemy HP x${L.hpMult}, attack x${L.atkMult} | More enemies, still easy to tough |
| Hero between levels | fresh every level | keeps every upgrade, healed at the chest; a retry starts from the level's entry | The upgrades carry the run |
| Boost cards | all the same | rare (blue, x2, 15%) and epic (gold, x3, 4%); boss kills always offer a rare | Something to hope for |
| Stack exponent | 1.9 | 1.7 | 5 stacks dealt 21x one stack; now 15x |
| Combo power / per kill | 6 / +0.5 | 5 / +0 (boosts only) | Max finishers can't outgrow the bosses |
| Boosts: damage / combo power | +20% / +1 | +15% / +0.5 | Many boost picks per run now (one per kill) |
| Heal on kill | 15% | 20% | Longer boss fights between heals |
| Miss self-damage (Classic) | 3 | 1 | Misses alone cost a 70% player about 100 HP a level |
| Bomb damage / group spawn interval | 15 / x1.6 | 40 / x0.8 | Bombs still matter; group fights are busy |

## Reading it

- **85% player, Level 1:**
  - wins ${pct(a1.winRate)} first try;
  - fights ramp ${a1.stageSec.map((x) => x.toFixed(0)).join(' / ')} s from the first Slime to the boss, and nearly every loss is at the boss;
  - attack grows x${num(a1.bossAtkGrowth)} by the boss, and fights still get longer, so there is no snowball.
- **85% player, Level 2:**
  - starts with ${a2.heroAtk.toFixed(1)} attack and every boost they took;
  - wins ${pct(a2.winRate)} first try, ${num(a2.attempts)} tries on average;
  - fights ramp ${a2.stageSec.map((x) => x.toFixed(0)).join(' / ')} s.
- **Bosses:** HP is ${num(a1.bossVsMaxFinisher)}x (Level 1) and ${num(a2.bossVsMaxFinisher)}x (Level 2) one max-stack finisher at the hero's stats
  when the boss appears, so each takes at least two. No run could one-shot either.
- **70% players** need about ${num(row(0.7, 0).attempts)} tries for Level 1; **95%** almost never lose it.
`;
  writeFileSync('docs/balance.md', md);
  process.stderr.write(`\nAFTER\n${table(a)}\n\nBEFORE\n${table(b)}\n`);
}, 3_600_000);
