// The campaign report: npm run campaign. Plays the story through every region for each hero at 85% (a fresh profile
// per run: Greenmarch from the start, then the next region's fresh run with the gear and levels earned), and prints
// each act's first-try clear and boss first fight per hero, with each hero's gap to Rowan. Writes
// docs/balance-campaign.md (docs/balance.md quotes it).
//   HEROES=rowan,sable  RUNS=150  ACC=0.85  REGIONS=2  OUT=path
import { writeFileSync } from 'node:fs';
import { it } from 'vitest';
import { balanceCampaign, TYPICAL_ACCURACY, type ActRow } from '../../src/core/bot';
import { HERO_IDS, HEROES, type HeroId } from '../../src/data/heroes';
import { REGIONS } from '../../src/data/regions';
import { cloneTuning } from '../../src/core/tuning';

const RUNS = Number(process.env.RUNS ?? 150);
const ACC = Number(process.env.ACC ?? TYPICAL_ACCURACY);
const REG = Number(process.env.REGIONS ?? REGIONS.length);
const HERO_LIST = (process.env.HEROES ? process.env.HEROES.split(',') : HERO_IDS) as HeroId[];
const OUT = process.env.OUT ?? 'docs/balance-campaign.md';

const pct = (v: number) => (Number.isFinite(v) ? `${Math.round(v * 100)}%` : '-');
const num = (v: number) => (Number.isFinite(v) ? v.toFixed(1) : '-');

it('campaign balance per hero', () => {
  const t = cloneTuning();
  const by: Record<string, ActRow[]> = {};
  const t0 = Date.now();
  for (const h of HERO_LIST) {
    by[h] = balanceCampaign(t, [ACC], RUNS, 1, h, REG);
    console.log(`${h}: ${((Date.now() - t0) / 1000).toFixed(0)} s`);
  }
  const acts = by[HERO_LIST[0]].map((r) => r.act);
  const head = `| Hero | ${acts.map((a) => `Act ${a + 1}: first try / boss`).join(' | ')} |`;
  const sep = `|---|${acts.map(() => '---').join('|')}|`;
  const rowan = by.rowan;
  const body = HERO_LIST.map((h) => {
    const cells = by[h].map((r, i) => {
      const gap = rowan && h !== 'rowan' ? ` (${Math.round((r.firstTry - rowan[i].firstTry) * 100) >= 0 ? '+' : ''}${Math.round((r.firstTry - rowan[i].firstTry) * 100)})` : '';
      return `**${pct(r.firstTry)}**${gap} / ${pct(r.bossFirstTry)}`;
    });
    return `| ${HEROES[h].name} | ${cells.join(' | ')} |`;
  });
  const detail = HERO_LIST.map((h) =>
    [
      `### ${HEROES[h].name}`,
      '| Act | Reached | First try | Clear (6 tries) | Boss first fight | Fight / elite / boss s | HP into boss | Level at boss | Misses per tap | Hits taken / min | Lost at fight / elite / boss |',
      '|---|---|---|---|---|---|---|---|---|---|---|',
      ...by[h].map(
        (r) =>
          `| ${r.act + 1} | ${pct(r.reached / r.runs)} | **${pct(r.firstTry)}** | ${pct(r.clearRate)} | **${pct(r.bossFirstTry)}** | ${Math.round(r.fightSec)} / ${Math.round(r.eliteSec)} / ${Math.round(r.bossSec)} | ${pct(r.hpAtBoss)} | ${num(r.levelAtBoss)} | ${pct(r.missRate)} | ${num(r.hitsTakenPerMin)} | ${r.lostAt.fight ?? 0} / ${r.lostAt.elite ?? 0} / ${r.lostAt.boss ?? 0} |`,
      ),
    ].join('\n'),
  );
  const md = [
    `# Campaign balance (${pct(ACC)} player, ${RUNS} runs per hero)`,
    '',
    'Generated by `npm run campaign`. Each run: a fresh profile, the story from Greenmarch on; a later region is played',
    "from the hero that won the region before it (its gear and levels), so its rows count only the runs that got there.",
    '',
    head,
    sep,
    ...body,
    '',
    ...detail,
    '',
  ].join('\n');
  writeFileSync(OUT, md);
  console.log(md);
});
