// npm run retarget: re-aim the difficulty curve at a player of a given accuracy (ACC=0.62 npm run retarget).
// The curve's targets stay what the playtester liked; only who they're set for changes:
//   Act 1 a gentle start (99% first try), Act 2 a step up (87% first try), the Boar King the real test (70% of first
//   fights won), each with the gear found on the way.
// It searches one multiplier per act (enemy HP and attack together), act by act, and writes docs/retarget.md with the
// numbers and a JSON snippet for the tuning panel's "Paste JSON".
import { writeFileSync } from 'node:fs';
import { it } from 'vitest';
import { balance, TYPICAL_ACCURACY } from '../../src/core/bot';
import { cloneTuning, type Tuning } from '../../src/core/tuning';

const ACC = Number(process.env.ACC ?? TYPICAL_ACCURACY);
const RUNS = Number(process.env.RUNS ?? 300);
const TARGETS = [
  { act: 0, what: 'first-try clear', key: 'firstTry' as const, target: 0.99 },
  { act: 1, what: 'first-try clear', key: 'firstTry' as const, target: 0.87 },
  { act: 2, what: 'Boar King first fight won', key: 'bossFirstTry' as const, target: 0.7 },
];

it('retarget the difficulty curve', () => {
  const base = cloneTuning();
  const t = cloneTuning();
  const mults: number[] = [];
  const lines: string[] = [];
  for (const g of TARGETS) {
    const score = (m: number): number => {
      const tt: Tuning = JSON.parse(JSON.stringify(t));
      tt.acts[g.act].hpMult = base.acts[g.act].hpMult * m;
      tt.acts[g.act].atkMult = base.acts[g.act].atkMult * m;
      const row = balance(tt, [ACC], RUNS, 17, 6, g.act + 1)[g.act];
      return row[g.key];
    };
    // harder (bigger m) -> lower odds; bisect on log(m)
    let lo = Math.log(0.25);
    let hi = Math.log(4);
    for (let i = 0; i < 9; i++) {
      const mid = (lo + hi) / 2;
      if (score(Math.exp(mid)) > g.target) lo = mid;
      else hi = mid;
    }
    const m = Math.exp((lo + hi) / 2);
    mults.push(m);
    t.acts[g.act].hpMult = base.acts[g.act].hpMult * m;
    t.acts[g.act].atkMult = base.acts[g.act].atkMult * m;
    const got = score(m);
    lines.push(`| ${g.act + 1} | ${g.what}: ${Math.round(g.target * 100)}% | ${Math.round(got * 100)}% | x${m.toFixed(2)} | ${t.acts[g.act].hpMult.toFixed(2)} | ${t.acts[g.act].atkMult.toFixed(2)} |`);
    process.stderr.write(`act ${g.act + 1}: x${m.toFixed(2)} -> ${Math.round(got * 100)}%\n`);
  }
  const json = JSON.stringify({ tuning: { acts: t.acts.map((a) => ({ hpMult: Math.round(a.hpMult * 100) / 100, atkMult: Math.round(a.atkMult * 100) / 100 })) } });
  const md = `# Difficulty retargeted for a ${Math.round(ACC * 100)}% player

Generated by \`ACC=${ACC} npm run retarget\` (\`tests/balance/retarget.run.ts\`), ${RUNS} runs per step. The defaults are set
for a ${Math.round(TYPICAL_ACCURACY * 100)}% player. This keeps the same curve (a gentle Act 1, a step up in Act 2, the Boar King as the
real test, with the gear found on the way) for a player of the measured accuracy (the gear panel shows it).

| Act | Target | Result | Enemy HP and attack | hpMult | atkMult |
|---|---|---|---|---|---|
${lines.join('\n')}

To try it on the phone: gear panel > Export > Paste JSON, and paste:

\`\`\`json
${json}
\`\`\`

To make it the default, put the hpMult / atkMult values into \`src/data/greenmarch.ts\`, set \`TYPICAL_ACCURACY\` in
\`src/core/bot.ts\` to ${ACC}, and re-run \`npm test\` and \`npm run balance\`.
`;
  writeFileSync('docs/retarget.md', md);
  process.stderr.write(`\n${md}\n`);
}, 3_600_000);
