// The player's real accuracy (pure; no DOM), measured the way the balance bot defines it: the share of plain yellow
// blocks (nominal width) they would hit at the starting cursor speed.
//
// Every tap aimed at a yellow block (one it hit, or a miss whose nearest block was a yellow) gives a timing error:
// how many ms before (-) or after (+) the cursor crossed the block's center. Only clear-cut taps count: the yellow had
// no other block and no wall turn within ISOLATION_MS of it, so the tap can't have been meant for something else.
// From those: a robust center (median) and spread (median absolute deviation, which the odd wild tap barely moves).
// In a real fight a tap can't come before the block was seen, or right on the heels of the last tap, and a wild one
// lands nearer some other block; so the raw spread reads a little tight for sloppy players. SD_CALIBRATION maps it to
// the bot's timing spread (bots of known accuracy, `npm run calibrate`), then the bot's own definition gives the
// accuracy: the share of plain yellows that spread (and that average lateness) would hit at the starting speed.
// tests/unit/accuracy.test.ts checks that bots of known accuracy read back right.

import type { Tuning } from './tuning';

/** Samples kept for the running number, and act-clear entries kept in the history. */
export const RECENT_MAX = 600;
export const HISTORY_MAX = 40;
/** Fewer samples than this and there is no number yet. */
export const MIN_SAMPLES = 20;
/** A tap further than this from any yellow wasn't aimed at one. */
export const AIM_WINDOW_MS = 300;
/** A yellow counts only if no other block (and no wall, where the cursor turns) is this close to it, in cursor time. */
export const ISOLATION_MS = 150;

/**
 * Raw spread (ms, as measured in fights) -> the bot's timing spread (ms) that produces it, for the default tuning.
 * Generated by `npm run calibrate` (tests/balance/calibrate.run.ts); re-run it after changing block widths, the
 * cursor or the acts' pace (tests/unit/accuracy.test.ts fails when it drifts).
 */
export const SD_CALIBRATION: Array<[number, number]> = [
  [0, 0],
  [19.3, 19.8],
  [26.7, 28.1],
  [34.1, 36.2],
  [41.5, 42.3],
  [46, 50.3],
  [54.9, 60.1],
  [62.3, 71.2],
  [72.6, 83],
  [78.6, 105.2],
  [84.5, 138.8],
  [94.9, 198],
];

/** The bot's timing spread for a raw measured spread (piecewise linear through SD_CALIBRATION). */
export function calibratedSd(raw: number): number {
  const c = SD_CALIBRATION;
  if (raw <= c[0][0]) return c[0][1];
  for (let i = 1; i < c.length; i++)
    if (raw <= c[i][0]) {
      const k = (raw - c[i - 1][0]) / Math.max(1e-9, c[i][0] - c[i - 1][0]);
      return c[i - 1][1] + k * (c[i][1] - c[i - 1][1]);
    }
  const [a, b] = [c[c.length - 2], c[c.length - 1]];
  return b[1] + ((raw - b[0]) * (b[1] - a[1])) / Math.max(1e-9, b[0] - a[0]);
}
/** The bot's share of lapses (taps that go badly wrong); the estimate assumes the same. */
export const LAPSE = 0.03;

export interface AccEntry {
  at: number; // ms since epoch
  act: number; // 0-based
  acc: number; // 0..1
  n: number; // taps measured
  sd: number; // timing spread, ms
  bias: number; // average lateness, ms (+ = late)
}

export interface AccuracyLog {
  recent: number[]; // the last RECENT_MAX timing errors, ms
  history: AccEntry[]; // one per act cleared, newest last
}

export const newAccuracyLog = (): AccuracyLog => ({ recent: [], history: [] });

export interface AccEstimate {
  acc: number;
  sd: number; // timing spread (calibrated), ms
  rawSd: number; // as measured
  bias: number;
  n: number;
}

/** The raw spread and lateness of a set of timing errors (null with too few). */
export function rawSpread(errs: number[]): { sd: number; bias: number; n: number } | null {
  const xs = errs.filter((e) => Number.isFinite(e) && Math.abs(e) <= AIM_WINDOW_MS);
  if (xs.length < MIN_SAMPLES) return null;
  const bias = median(xs);
  return { sd: Math.max(1, 1.4826 * median(xs.map((e) => Math.abs(e - bias)))), bias, n: xs.length };
}

/** The bot's accuracy for a timing spread and average lateness (ms). */
export function accuracyFor(t: Tuning, sd: number, bias = 0): number {
  const half = yellowHalfMs(t);
  const p = phi((half - bias) / sd) - phi((-half - bias) / sd);
  return Math.max(0, Math.min(1, (1 - LAPSE) * p));
}

function erf(x: number): number {
  // Abramowitz-Stegun 7.1.26 (|error| < 1.5e-7)
  const s = Math.sign(x);
  const a = Math.abs(x);
  const t = 1 / (1 + 0.3275911 * a);
  const y = 1 - ((((1.061405429 * t - 1.453152027) * t + 1.421413741) * t - 0.284496736) * t + 0.254829592) * t * Math.exp(-a * a);
  return s * y;
}

const phi = (x: number) => 0.5 * (1 + erf(x / Math.SQRT2));

/** Half the time window (ms) in which a tap lands on a plain yellow at the starting speed (the bot's definition). */
export function yellowHalfMs(t: Tuning): number {
  const v = 1 / t.cursor.basePassSec;
  return (((t.blocks.attackWidth + t.cursor.widthFrac) / 2 / v) + t.judge.graceMs / 1000) * 1000;
}

function median(xs: number[]): number {
  const s = xs.slice().sort((a, b) => a - b);
  const m = s.length >> 1;
  return s.length % 2 ? s[m] : (s[m - 1] + s[m]) / 2;
}

/** Accuracy from timing errors (ms), or null with too few of them. */
export function estimateAccuracy(t: Tuning, errs: number[]): AccEstimate | null {
  const r = rawSpread(errs);
  if (!r) return null;
  const sd = Math.max(1, calibratedSd(r.sd));
  return { acc: accuracyFor(t, sd, r.bias), sd, rawSd: r.sd, bias: r.bias, n: r.n };
}

/** Add a fight's timing errors to the running window. */
export function addSamples(log: AccuracyLog, errs: number[]): void {
  for (const e of errs) if (Number.isFinite(e)) log.recent.push(Math.round(e));
  if (log.recent.length > RECENT_MAX) log.recent.splice(0, log.recent.length - RECENT_MAX);
}

/** An act was cleared: its accuracy goes into the history (null if too few taps to say). */
export function recordActAccuracy(t: Tuning, log: AccuracyLog, act: number, errs: number[], now = Date.now()): AccEntry | null {
  const e = estimateAccuracy(t, errs);
  if (!e) return null;
  const entry: AccEntry = { at: now, act, acc: e.acc, n: e.n, sd: Math.round(e.sd), bias: Math.round(e.bias) };
  log.history.push(entry);
  if (log.history.length > HISTORY_MAX) log.history.splice(0, log.history.length - HISTORY_MAX);
  return entry;
}

/** A saved log in current form (junk is dropped). */
export function readAccuracyLog(data: unknown): AccuracyLog {
  const d = data as AccuracyLog | null;
  const n = (v: unknown): v is number => typeof v === 'number' && Number.isFinite(v);
  if (!d || typeof d !== 'object') return newAccuracyLog();
  const recent = Array.isArray(d.recent) ? d.recent.filter(n).slice(-RECENT_MAX) : [];
  const history = Array.isArray(d.history)
    ? d.history.filter((h) => h && [h.at, h.act, h.acc, h.n, h.sd, h.bias].every(n)).slice(-HISTORY_MAX)
    : [];
  return { recent, history };
}
